name: Build SDL Doom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Emscripten
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Build SDL Doom
        run: |
          set -e
          OUTPUT_DIR=$(pwd)
          cd sdldoom-1.10
          SOURCE_DIR="."
          mkdir -p "$OUTPUT_DIR"
          SRC_FILES=$(find "$SOURCE_DIR" -name '*.c')
          OUTPUT_HTML="$OUTPUT_DIR/build/index.html"
          emcc $SRC_FILES -o "$OUTPUT_HTML" --preload-file "$SOURCE_DIR" --preload-file doom2.wad -s ALLOW_MEMORY_GROWTH=1 --shell-file "$OUTPUT_DIR/shell.html" -s USE_SDL=1 2>../error.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdl-doom-build
          path: build/