name: Build WebLyne DOOM®

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Emscripten
        run: choco install emscripten

      - name: Compile WebLyne DOOM®
        run: .\build.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: weplyne-doom-build
          path: build/