name: Deploy CodexAI

on:
  push:
    branches:
      -  

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to WebsiteFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.197.91.6
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          server-dir: /public_html/codex