name: Build and Deploy WebLyne Doom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y emscripten automake libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev

      - name: Run clean script
        run: ./scripts/clean.sh
        
      - name: Run build script
        run: ./scripts/build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5
