name: Build and Deploy SDL Doom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo Setting up Emscripten...
          choco install emscripten
          echo Emscripten is ready.

      - name: Compile WebLyne Doom
        shell: pwsh
        run: |
          # Enable strict error handling
          $ErrorActionPreference = "Stop"
        
          # Set output directory
          $OUTPUT_DIR = Join-Path -Path (Get-Location) -ChildPath "build"
          if (!(Test-Path -Path $OUTPUT_DIR)) {
              New-Item -ItemType Directory -Path $OUTPUT_DIR | Out-Null
          }
        
          # Change directory to source folder
          Set-Location -Path "sdldoom-1.10"

          # Collect source files
          $SRC_FILES = Get-ChildItem -Filter *.c | ForEach-Object { $_.FullName }
        
          # Set output HTML file
          $OUTPUT_HTML = Join-Path -Path $OUTPUT_DIR -ChildPath "index.html"
        
          # Compile using emcc (no concatenation needed)
          & emcc $SRC_FILES -o $OUTPUT_HTML `
            --preload-file . `
            --preload-file doom.wad `
            -s ALLOW_MEMORY_GROWTH=1 `
            --shell-file ..\shell.html `
            -s USE_SDL=1 2> ..\error.log
        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: 'build/'

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: 'build/'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
