name: Build and Deploy WebLyne

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Specific Emscripten Version
      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 3.1.40
          ./emsdk activate 3.1.40
          source ./emsdk_env.sh

      # Step 3: Compile WebLyne
      - name: Compile WebLyne
        run: |
          mkdir -p build
          emcc sdldoom-1.10/*.c -o build/index.html \
            --preload-file sdldoom-1.10 \
            --preload-file sdldoom-1.10/doom.wad \
            -s ALLOW_MEMORY_GROWTH=1 \
            --shell-file shell.html \
            -s USE_SDL=1

      # Step 4: Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 5: Upload build artifacts for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/'

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
